/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 car2.gltf 
Author: DisneyCars (https://sketchfab.com/supercarmodels)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/1978-lancia-037-stradale-9c9348b5649743bea57ff51aa38c925f
Title: 1978 Lancia 037 Stradale
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Car2(props) {
  const { nodes, materials } = useGLTF('/car2.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['1weld1Mtl']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['50percentmaterialmesh1Mtl']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['50percentmaterialmesh2Mtl']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.AemGauges1Mtl} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.BackCover1Mtl} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Belt1Mtl} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Brakes1Mtl} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Brakes2Mtl} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.DiceMisc1Mtl} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.F1Mtl} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Fans1Mtl} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Iphone5s1Mtl} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Meshpart106Mtl} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Meshpart13Mtl} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Meshpart16Mtl} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.Meshpart1Mtl} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.Meshpart2Mtl} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.Meshpart35Mtl} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.Meshpart3Mtl} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.Meshpart46Mtl} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.Meshpart50Mtl} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.Meshpart51Mtl} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.Meshpart55Mtl} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.Meshpart76Mtl} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.Meshpart79Mtl} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.Meshpart7Mtl} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.Meshpart87Mtl} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.Misc1Mtl} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.Part1Mtl} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.Part3Mtl} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.Radio1Mtl} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.Radio2Mtl} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.Radio7Mtl} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.RearDifferential1Mtl} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.Seat1Mtl} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.SsrFormulaSpf1Mtl} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.SteeringWheel1Mtl} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.Takata1Mtl} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.Union1Mtl} />
      </group>
    </group>
  )
}

useGLTF.preload('/car2.gltf')
