/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 lake.gltf 
Author: Yerbol Kopeyev (https://sketchfab.com/yerbol.kopeyev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stuck-excavators-on-lake-sairan-almaty-93340ffbaa2d4b36888d771519b2a7c5
Title: Stuck excavators on Lake Sairan. Almaty
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Lake(props) {
  const { nodes, materials } = useGLTF('/lake.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Tile_-1__Tile_1.obj_Default__623_vis']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Tile_-1__Tile_1.obj_Default__623_vis']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['Tile_-1__Tile_1.obj_Default__623_vis']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Tile_-1__Tile_1.obj_Default__623_vis']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Tile_-3__Tile_2.obj_Default__623_vis']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Tile_-3__Tile_2.obj_Default__623_vis']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Tile_-3__Tile_2.obj_Default__623_vis']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['Tile_-5__Tile_3.obj_Default__623_vis']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['Tile_-5__Tile_3.obj_Default__623_vis']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['Tile_-7__Tile_4.obj_Default__623_vis']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['Tile_-7__Tile_4.obj_Default__623_vis']} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['Tile_-9__Tile_5.obj_Default__623_vis']} />
      </group>
    </group>
  )
}

useGLTF.preload('/lake.gltf')
