/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 park.gltf 
Author: Idmental (https://sketchfab.com/idmental.id)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/parking-garage-free-download-5310b7d77b70427d936ec4253fff679c
Title: Parking garage [FREE DOWNLOAD]
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Park(props) {
  const { nodes, materials } = useGLTF('/park.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.027}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Mat.1']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.glass} />
      </group>
    </group>
  )
}

useGLTF.preload('/park.gltf')
